export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGUOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS'
    // USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST'
}

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST : 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS : 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE : 'GET_ALL_CATEGORY_FAILURE',

    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE',

    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE: 'DELETE_CATEGORIES_FAILURE'
}

export const productConstants = {
    GET_ALL_PRODUCT_REQUEST : 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS : 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE : 'GET_ALL_PRODUCT_FAILURE'
}

export const initialDataConstants = {
    GET_ALL_INITIALDATA_REQUEST : 'GET_ALL_INITIALDATA_REQUEST',
    GET_ALL_INITIALDATA_SUCCESS : 'GET_ALL_INITIALDATA_SUCCESS',
    GET_ALL_INITIALDATA_FAILURE : 'GET_ALL_INITIALDATA_FAIL'
}